### ISSUE TITLE
Build error with g++ 4.8.5

### ISSUE THREAD

**Issue by ryosa** [jcdutton/libbeauty#17]
Building libbeauty with g++ 4.8.5, I got the following error. What is wrong?

``In file included from ../../../../../include/rev.h:33:0,
                 from decode_asm_X86_64.cpp:28:
decode_asm_X86_64.cpp: In function 'int llvm::DecodeAsmOpInfoCallback(void*, uint64_t, uint64_t, uint64_t, int, void*)':
../../../../../include/debug_llvm.h:47:119: warning: format '%x' expects argument of type 'unsigned int', but argument 7 has type 'uint64_t {aka long unsigned int}' [-Wformat=]
 #define debug_print(module, level, format, ...) dbg_print(__FUNCTION__, __LINE__, module, level, format, ##__VA_ARGS__)
                                                                                                                       ^
decode_asm_X86_64.cpp:47:2: note: in expansion of macro 'debug_print'
  debug_print(DEBUG_INPUT_DIS, 1, "NumOperands = 0x%x, Offset = 0x%x, Size = 0x%x\n", num_operands, Offset, Size);
  ^
../../../../../include/debug_llvm.h:47:119: warning: format '%x' expects argument of type 'unsigned int', but argument 8 has type 'uint64_t {aka long unsigned int}' [-Wformat=]
 #define debug_print(module, level, format, ...) dbg_print(__FUNCTION__, __LINE__, module, level, format, ##__VA_ARGS__)
                                                                                                                       ^
decode_asm_X86_64.cpp:47:2: note: in expansion of macro 'debug_print'
  debug_print(DEBUG_INPUT_DIS, 1, "NumOperands = 0x%x, Offset = 0x%x, Size = 0x%x\n", num_operands, Offset, Size);
  ^
decode_asm_X86_64.cpp: In member function 'int llvm::DecodeAsmX86_64::setup()':
decode_asm_X86_64.cpp:85:52: error: expected ')' before 'PRIx64'
  debug_print(DEBUG_INPUT_DIS, 1, "TheTarget = 0x%" PRIx64 "\n", TheTarget);
                                                    ^

**Comment by jcdutton** [comment]
I do not see these problems here. Please re-open if they are still a problem.
