### ISSUE TITLE
id27.txt test failure

### ISSUE THREAD

**Issue by dtzWill** [jcdutton/libbeauty#20]
Running the lit test suite, I'm seeing all the tests pass (hooray!) other than `id27.txt` which seemed strange enough to report :).

This behavior happened using the LLVM 3.9 build from yesterday (066cfe058e2b6e78b3ce89440a38f1948abb58f9) and when building against LLVM 4.0 using today's latest (cf256274eed2d2b4205976cd54ea938431ace5b2).

Here's the test log:

```
******************** TEST 'LLVM :: id27.txt' FAILED ********************
Script:
--
test_id /tmp/nix-build-libbeauty-2017-04-15.drv-0/libbeauty-cf256274eed2d2b4205976cd54ea938431ace5b2-src/libbeauty/test/tests/id27.txt | FileCheck /tmp/nix-build-libbeauty-2017-04-15.drv-0/libbeauty-cf256274eed2d2b4205976cd54ea938431ace5b2-src/libbeauty/test/tests/id27.txt
--
Exit Code: 1

Command Output (stderr):
--
/tmp/nix-build-libbeauty-2017-04-15.drv-0/libbeauty-cf256274eed2d2b4205976cd54ea938431ace5b2-src/libbeauty/test/tests/id27.txt:5:10: error: expected string not found in input
# CHECK: getInstruction Size = 0x3
         ^
<stdin>:1:1: note: scanning from here
getInstruction Size = 0x2
^

--

********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90..
Testing Time: 2.56s
********************
Failing Tests (1):
    LLVM :: id27.txt

  Expected Passes    : 58
  Unexpected Failures: 1

```

**Comment by dtzWill** [comment]
I have not applied the provided LLVM patch, since the suggested check suggested it wasn't needed (and I think that's checked as its own lit test anyway?), but LMK if lacking that patch is likely related to this issue and I'll give it a go :).

**Comment by dtzWill** [comment]
Running by hand shows the very next line of output, which makes things quite a bit clearer:

```console
$ ./test/test_id ./test/tests/id27.txt 
getInstruction Size = 0x2
Unhandled instruction, not yet implemented convert
```
Assuming that's indeed the expected behavior currently, then all is well--mostly I wanted to make sure I wasn't building things incorrectly or the like.  Don't mean to bug about known not-yet-implemented bits :).

**Comment by jcdutton** [comment]
Failure of test "id27.txt" is as expected currently.
